[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "8.2.0"
rocket = { version = "0.5.1", features = ["json"] }
tokio = "1.48.0"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
